modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
[[mods]]
modId="tutorialmod"
version="${file.jarVersion}"
displayName="Tutorial Mod"
logoFile="examplemod.png"
credits="built by christian colaiezzi with use of CY4's modding youtube
https://www.youtube.com/playlist?list=PLlbkaeFHn13HQlW5Pb7Gf-xLJoAlfVbNU"
description='''
This mod is to add "Beskar" metal into minecraft as a natural resource that can be smelted and crafted with.

I sure hope that this works
'''

[[dependencies.tutorialmod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
